### PR TITLE
add Dir#mktmpdir

### PR DESCRIPTION
**Pull request by i110**
Mostly taken from https://github.com/ruby/ruby/blob/trunk/lib/tmpdir.rb, but adjusted so that it works within mruby.

### CODE REVIEW

**Comment by tsahara** [comment]
Thank you for sending the patch.  But we cannot merge it as is because the license of the code taken from cruby is not clear.

**Comment by i110** [comment]
@tsahara Thank you for the comment, sorry for my long absence. I totally rewrote the method without porting CRuby's code directly, and I think it conforms to the spec at https://docs.ruby-lang.org/ja/latest/method/Dir/s/mktmpdir.html. There might still be a few similar portion to CRuby's one, but I think it's inevitable due to the spec.

**Comment by i110** [comment]
@tsahara thank you for reporting the issue. I believe https://github.com/iij/mruby-tempfile/pull/9/commits/78cecc1228a62672b21ebe217bcaca6d890c1f4b fixed that problem.

Aside to that, https://github.com/iij/mruby-tempfile/blob/master/mrblib/tempfile.rb#L21-L25 has the same issue when we build mruby with MRB_INT16, because t.usec can be up to 999999 which is bigger than MRB_INT_MAX.  I think it's easy to fix, but I didn't since I had no idea why we're using `t.usec` as max argument. What do you think?

By the way, I think you already know, but mruby-io and mruby-pack seem to have the same issue around MRB_INT16.
```
Fail: IO#close_on_exec (mrbgems: mruby-io)
 - Assertion[1] Failed: Expected false to be true
    Expected: true
      Actual: false
Fail: pack/unpack "U" (mrbgems: mruby-pack)
 - Assertion[10] Failed: Expected to raise [RangeError], not
      Class: <TypeError>
    Message: can't convert Float to Integer (Float#to_int gives Float)
 - Assertion[12] Failed: Expected to raise [RangeError], not
      Class: <TypeError>
    Message: can't convert Float to Integer (Float#to_int gives Float)
```

**Comment by tsahara** [comment]
Thank you for fixing issues on non-64bit machines.

>Aside to that, https://github.com/iij/mruby-tempfile/blob/master/mrblib/tempfile.rb#L21-L25 has the same issue when we build mruby with MRB_INT16, because t.usec can be up to 999999 which is bigger than MRB_INT_MAX (0x7fff).

I don't know the reason but I'm sure that it is not a very good way to generate a random number sequence :)

**Pull request merged**
